/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
   export interface GlobalComponents {
      ElAside: typeof import('element-plus/es')['ElAside'];
      ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
      ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
      ElButton: typeof import('element-plus/es')['ElButton'];
      ElContainer: typeof import('element-plus/es')['ElContainer'];
      ElForm: typeof import('element-plus/es')['ElForm'];
      ElFormItem: typeof import('element-plus/es')['ElFormItem'];
      ElHeader: typeof import('element-plus/es')['ElHeader'];
      ElInput: typeof import('element-plus/es')['ElInput'];
      ElLink: typeof import('element-plus/es')['ElLink'];
      ElMain: typeof import('element-plus/es')['ElMain'];
      ElMenu: typeof import('element-plus/es')['ElMenu'];
      ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
      ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
      ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
      IEpFold: typeof import('~icons/ep/fold')['default'];
      IEpRight: typeof import('~icons/ep/right')['default'];
      IEpSetting: typeof import('~icons/ep/setting')['default'];
      RouterLink: typeof import('vue-router')['RouterLink'];
      RouterView: typeof import('vue-router')['RouterView'];
   }
}
